[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --ignore-scripts --prefix app"]

[phases.build]
cmds = ["npm run build --prefix app"]

[start]
cmd = "npm start --prefix app -- -p $PORT"
